# Generated by Django 6.0.1 on 2026-01-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("assistant", "Assistant")],
                default="user",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="description",
            field=models.CharField(max_length=500),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["-date_created"], name="conversatio_date_cr_0c2de3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "date_created"],
                name="conversatio_convers_dddafb_idx",
            ),
        ),
    ]
