# Generated by Django 4.2.7 on 2026-01-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0002_conversation_title_message_role_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="conversation",
            name="conversatio_date_cr_0c2de3_idx",
        ),
        migrations.RemoveIndex(
            model_name="message",
            name="conversatio_convers_dddafb_idx",
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["conversation_id", "-date_created"],
                name="conversatio_convers_2a0c98_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["message_id", "conversation", "date_created"],
                name="conversatio_message_d086d2_idx",
            ),
        ),
    ]
