# Generated by Django 4.2.7 on 2026-01-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "conversations",
            "0003_remove_conversation_conversatio_date_cr_0c2de3_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="conversation",
            name="conversatio_convers_2a0c98_idx",
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["conversation_id", "date_created"],
                name="conversatio_convers_ac67cc_idx",
            ),
        ),
    ]
